"""
schemas/quiz_schemas.py

Day 6 — Pydantic request and response models for the Quiz API.

Endpoints:
  POST /quiz/generate
  GET  /quiz/{quiz_id}
  POST /quiz/{quiz_id}/submit
  GET  /quiz/history

Quiz question structure (single MCQ):
  {
    "question": "...",
    "options": ["A", "B", "C", "D"],
    "correct_answer": "A",
    "topic": "...",
    "explanation": "..."
  }

Grading is ALWAYS deterministic: submitted_answer == correct_answer.
The LLM never decides correctness.
"""

from typing import List, Optional
from pydantic import BaseModel, field_validator


# ─── Single MCQ question ───────────────────────────────────────────────────────

class QuizQuestion(BaseModel):
    """
    A single multiple-choice question generated by the Quiz Agent.

    correct_answer must be one of the options.
    explanation is generated by the LLM to guide the student after submission.
    """
    question: str
    options: List[str]
    correct_answer: str
    topic: str
    explanation: str = ""

    @field_validator("question")
    @classmethod
    def validate_question(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("question must not be empty")
        return v

    @field_validator("options")
    @classmethod
    def validate_options(cls, v: List[str]) -> List[str]:
        if len(v) < 2:
            raise ValueError("options must contain at least 2 choices")
        stripped = [o.strip() for o in v]
        if any(not o for o in stripped):
            raise ValueError("options must not contain empty strings")
        return stripped

    @field_validator("correct_answer")
    @classmethod
    def validate_correct_answer(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("correct_answer must not be empty")
        return v

    @field_validator("topic")
    @classmethod
    def validate_topic(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("topic must not be empty")
        return v


# ─── Request schemas ───────────────────────────────────────────────────────────

class QuizGenerateRequest(BaseModel):
    """Body for POST /quiz/generate."""
    document_id: str
    topic: Optional[str] = None   # Optional topic hint; agent auto-detects weak topics if None
    num_questions: int = 5

    @field_validator("document_id")
    @classmethod
    def validate_document_id(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("document_id must not be empty")
        return v

    @field_validator("num_questions")
    @classmethod
    def validate_num_questions(cls, v: int) -> int:
        if v < 1 or v > 20:
            raise ValueError("num_questions must be between 1 and 20")
        return v


class QuizSubmitRequest(BaseModel):
    """Body for POST /quiz/{quiz_id}/submit."""
    answers: List[str]   # List of submitted answers, indexed to match questions

    @field_validator("answers")
    @classmethod
    def validate_answers(cls, v: List[str]) -> List[str]:
        if not v:
            raise ValueError("answers must not be empty")
        return [a.strip() for a in v]


# ─── Response schemas ──────────────────────────────────────────────────────────

class QuizResponse(BaseModel):
    """Response from POST /quiz/generate and GET /quiz/{quiz_id}."""
    quiz_id: str
    document_id: str
    topic: str
    questions: List[QuizQuestion]
    created_at: str


class QuestionResult(BaseModel):
    """Result for a single MCQ question after submission."""
    question: str
    submitted_answer: str
    correct_answer: str
    is_correct: bool            # Deterministic: submitted_answer == correct_answer
    explanation: str = ""


class QuizSubmitResponse(BaseModel):
    """Response from POST /quiz/{quiz_id}/submit."""
    quiz_id: str
    attempt_id: str
    score: int                  # Number of correct answers
    total: int                  # Total number of questions
    percentage: float           # score / total * 100  (calculated by app code, not LLM)
    results: List[QuestionResult]


class QuizHistoryItem(BaseModel):
    """One entry in the quiz history list."""
    quiz_id: str
    document_id: str
    topic: str
    num_questions: int
    created_at: str

    # Latest attempt summary (None if no attempt submitted yet)
    latest_attempt_id: Optional[str] = None
    latest_score: Optional[int] = None
    latest_percentage: Optional[float] = None
    latest_attempt_at: Optional[str] = None
